export const defaultPromptTemplate = [
  "Write 4 commit message in the conventional commit convention.",
  "",
  "commit messages should:",
  " - follow conventional commits",
  " - message format should be: <type>[optional scope]: <description>",
  " - description use {{locale}} language",
  " - contains most changes",
  "",
  "examples:",
  " - fix(authentication): add password regex pattern",
  " - feat(storage): add new test cases",
  "",
  "{{diff}}",
].join("\n");
